const ShopList = [
  {
    id: 1,
    image: 'https://imgur.com/Y4lPNVB.png',
    title: 'Minecraft SF 399 Fremont',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
    sale: 0.5,
  },
  {
    id: 2,
    image: 'https://imgur.com/NwGdzZd.png',
    title: 'Minecraft Apartment Buildings',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 3,
    image: 'https://imgur.com/PZcrKu1.png',
    title: 'Minecraft Great Mosque of Djenne',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 4,
    image: 'https://imgur.com/SMuV1gX.png',
    title: 'Minecraft Villa',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 5,
    image: 'https://imgur.com/AwXfCfo.png',
    title: 'Minecraft Church',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 6,
    image: 'https://imgur.com/odQ2aZQ.png',
    title: 'Minecraft Modern Villa',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
    sale: 0.5,
  },
  {
    id: 7,
    image: 'https://imgur.com/q0LS1MA.png',
    title: 'Minecraft Jardin Majorelle',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 8,
    image: 'https://imgur.com/qen5qgS.png',
    title: 'Minecraft SF Painted Ladies',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 9,
    image: 'https://imgur.com/sERWBDz.png',
    title: 'Minecraft SF Rincon Hill',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 10,
    image: 'https://imgur.com/QkWnsJA.png',
    title: 'Minecraft San Francisco',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
    sale: 0.5,
  },
  {
    id: 11,
    image: 'https://imgur.com/1TdpID5.png',
    title: 'Minecraft Volcano Isle',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 12,
    image: 'https://imgur.com/zqXD08a.png',
    title: 'Minecraft Japanese Island',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 13,
    image: 'https://imgur.com/xmFM0Fh.png',
    title: 'Minecraft Dino Skull Cave',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 14,
    image: 'https://imgur.com/HTxajnn.png',
    title: 'Minecraft The Gates of Nether',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
    sale: 0.5,
  },
  {
    id: 15,
    image: 'https://imgur.com/AAE5uLl.png',
    title: 'Minecraft Pirate Cliff',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 16,
    image: 'https://imgur.com/zxGZoB6.png',
    title: 'Minecraft Nordic Village',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 17,
    image: 'https://imgur.com/f3KnD7b.png',
    title: 'Minecraft Japanese Temple',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
    sale: 0.5,
  },
  {
    id: 18,
    image: 'https://imgur.com/Ucn6u7T.png',
    title: 'Minecraft Japanese Modern Villas',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 19,
    image: 'https://imgur.com/GBn3a00.png',
    title: 'Minecraft Medieval Castle',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 20,
    image: 'https://imgur.com/21aZq49.png',
    title: 'Minecraft Bali Aquapark',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
    sale: 0.5,
  },
  {
    id: 21,
    image: 'https://imgur.com/LtiAPOv.png',
    title: 'Minecraft Nobel Manor Hause',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 22,
    image: 'https://imgur.com/Tk8ubwf.png',
    title: 'Minecraft Aqua Palace',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 23,
    image: 'https://imgur.com/ZExpnSk.png',
    title: 'Minecraft Angler Bedwars Map',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
    sale: 0.5,
  },

  {
    id: 26,
    image: 'https://imgur.com/4UWXHCC.png',
    title: 'Minecraft Red Dragon',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
  {
    id: 27,
    image: 'https://imgur.com/sPua23R.png',
    title: 'Minecraft Small Japanese House',
    desc: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dignissimos illo, pariatur architecto nihil recusandae similique quod velit consequuntur ullam in.',
    price: 1,
  },
];

export default ShopList;
