export const Images = [
  {
    id: '1',
    imageSrc: 'https://imgur.com/Y4lPNVB.png',
    builder: 'rockyFeller',
    desc: 'Minecraft SF 399 Fremont',
    imgurAlbum: 'https://imgur.com/gallery/sFNwNOQ',
  },
  {
    id: '2',
    imageSrc: 'https://imgur.com/NwGdzZd.png',
    builder: 'rockyFeller',
    desc: 'Minecraft Apartment Buildings',
    imgurAlbum: 'https://imgur.com/gallery/wirARai',
  },
  {
    id: '3',
    imageSrc: 'https://imgur.com/PZcrKu1.png',
    builder: 'DristPl',
    desc: 'Minecraft Great Mosque of Djenne',
    imgurAlbum: 'https://imgur.com/gallery/3mMSeQX',
  },
  {
    id: '4',
    imageSrc: 'https://imgur.com/SMuV1gX.png',
    builder: 'rockyFeller',
    desc: 'Minecraft Villa',
    imgurAlbum: 'https://imgur.com/gallery/ekEFeoY',
  },
  {
    id: '5',
    imageSrc: 'https://imgur.com/AwXfCfo.png',
    builder: 'rockyFeller',
    desc: 'Minecraft Church',
    imgurAlbum: 'https://imgur.com/gallery/jWdlhEb',
  },
  {
    id: '6',
    imageSrc: 'https://imgur.com/odQ2aZQ.png',
    builder: 'rockyFeller',
    desc: 'Minecraft Modern Villa',
    imgurAlbum: 'https://imgur.com/gallery/6Mhjcw2',
  },
  {
    id: '7',
    imageSrc: 'https://imgur.com/q0LS1MA.png',
    builder: 'DristPl',
    desc: 'Minecraft Jardin Majorelle',
    imgurAlbum: 'https://imgur.com/gallery/Qly88Vk',
  },
  {
    id: '8',
    imageSrc: 'https://imgur.com/qen5qgS.png',
    builder: 'DristPl',
    desc: 'Minecraft SF Painted Ladies',
    imgurAlbum: 'https://imgur.com/gallery/F7HOAul',
  },
  {
    id: '9',
    imageSrc: 'https://imgur.com/sERWBDz.png',
    builder: 'DristPl',
    desc: 'Minecraft SF Rincon Hill',
    imgurAlbum: 'https://imgur.com/gallery/lLHnVm5',
  },
  {
    id: '10',
    imageSrc: 'https://imgur.com/QkWnsJA.png',
    builder: 'DristPl',
    desc: 'Minecraft San Francisco',
    imgurAlbum: 'https://imgur.com/gallery/0h6btKa',
  },
  {
    id: '11',
    imageSrc: 'https://imgur.com/1TdpID5.png',
    builder: 'rockyFeller',
    desc: 'Minecraft Volcano Isle',
    imgurAlbum: 'https://imgur.com/gallery/A4asikM',
  },
  {
    id: '12',
    imageSrc: 'https://imgur.com/zqXD08a.png',
    builder: 'rockyFeller',
    desc: 'Minecraft Japanese Island',
    imgurAlbum: 'https://imgur.com/gallery/ZwRwrga',
  },
  {
    id: '13',
    imageSrc: 'https://imgur.com/xmFM0Fh.png',
    builder: 'drummaks',
    desc: 'Minecraft Dino Skull Cave',
    imgurAlbum: 'https://imgur.com/gallery/0X37PAe',
  },
  {
    id: '14',
    imageSrc: 'https://imgur.com/HTxajnn.png',
    builder: 'drummaks',
    desc: 'Minecraft The Gates of Nether',
    imgurAlbum: 'https://imgur.com/gallery/zdUbZB8',
  },
  {
    id: '15',
    imageSrc: 'https://imgur.com/AAE5uLl.png',
    builder: 'drummaks',
    desc: 'Minecraft Pirate Cliff',
    imgurAlbum: 'https://imgur.com/gallery/2A4dY4L',
  },
  {
    id: '16',
    imageSrc: 'https://imgur.com/zxGZoB6.png',
    builder: 'drummaks',
    desc: 'Minecraft Nordic Village',
    imgurAlbum: 'https://imgur.com/gallery/uqFCzhe',
  },
  {
    id: '17',
    imageSrc: 'https://imgur.com/f3KnD7b.png',
    builder: 'drummaks',
    desc: 'Minecraft Japanese Temple',
    imgurAlbum: 'https://imgur.com/gallery/hy6lJTC',
  },
  {
    id: '24',
    imageSrc: 'https://imgur.com/moTnGNA.png',
    builder: 'drummaks',
    desc: 'Minecraft Cozy Cottage in a Cave',
    imgurAlbum: 'https://imgur.com/gallery/maaTFcM',
  },
  {
    id: '25',
    imageSrc: 'https://imgur.com/Epa73I1.png',
    builder: 'drummaks',
    desc: 'Minecraft Japanese Village',
    imgurAlbum: 'https://imgur.com/gallery/ZzLPOc1',
  },
  {
    id: '18',
    imageSrc: 'https://imgur.com/Ucn6u7T.png',
    builder: 'drummaks',
    desc: 'Minecraft Japanese Modern Villas',
    imgurAlbum: 'https://imgur.com/gallery/ofOMgIP',
  },
  {
    id: '19',
    imageSrc: 'https://imgur.com/GBn3a00.png',
    builder: 'TEAM_Lavarc',
    desc: 'Minecraft Medieval Castle',
    imgurAlbum: 'https://imgur.com/gallery/n4T6Ya0',
  },
  {
    id: '20',
    imageSrc: 'https://imgur.com/21aZq49.png',
    builder: 'drummaks',
    desc: 'Minecraft Bali Aquapark',
    imgurAlbum: 'https://imgur.com/gallery/6eUqCa9',
  },
  {
    id: '21',
    imageSrc: 'https://imgur.com/LtiAPOv.png',
    builder: 'drummaks',
    desc: 'Minecraft Nobel Manor Hause',
    imgurAlbum: 'https://imgur.com/gallery/JvD3OMn',
  },
  {
    id: '22',
    imageSrc: 'https://imgur.com/Tk8ubwf.png',
    builder: 'Fronikuniu',
    desc: 'Minecraft Aqua Palace',
    imgurAlbum: 'https://imgur.com/gallery/Lzx0kw6',
  },
  {
    id: '23',
    imageSrc: 'https://imgur.com/ZExpnSk.png',
    builder: 'Fronikuniu',
    desc: 'Minecraft Angler Bedwars Map',
    imgurAlbum: 'https://imgur.com/gallery/mQsYYQ3',
  },

  {
    id: '26',
    imageSrc: 'https://imgur.com/4UWXHCC.png',
    builder: 'Fronikuniu',
    desc: 'Minecraft Red Dragon',
    imgurAlbum: 'https://imgur.com/gallery/9Ih6eoy',
  },
  {
    id: '27',
    imageSrc: 'https://imgur.com/sPua23R.png',
    builder: 'drummaks',
    desc: 'Minecraft Small Japanese House',
    imgurAlbum: 'https://imgur.com/gallery/vnzMo9y',
  },
];
